version: "3.8"

services:
  app:
    build: .
    command: --reload
    volumes:
      - .:/opt/app/
    ports:
      - 80:8000
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: nrk_nynorsk
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
