version: "3.8"

services:
  app:
    image: henbruas/nrk_nynorsk:0.1.0
    ports:
      - 80:8000
    environment:
      ALLOWED_HOSTS: 127.0.0.1,localhost
      DB_HOST: db
      DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret_key
      DB_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - django_secret_key
      - postgres_password
    deploy:
      mode: replicated
      replicas: 2

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: nrk_nynorsk
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - db:/var/lib/postgresql/data
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nrk_nynorsk"]

secrets:
  django_secret_key:
    file: ./django_secret_key.txt
  postgres_password:
    file: ./postgres_password.txt

volumes:
  db:
