# Generated by Django 3.1rc1 on 2020-07-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nrk_nynorsk", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE INDEX nrk_nynorsk_article_ts_vector_idx ON nrk_nynorsk_article USING GIN (to_tsvector('norwegian'::regconfig, COALESCE("nrk_nynorsk_article"."title", '') || ' ' || COALESCE("nrk_nynorsk_article"."description", '')));""",
            "DROP INDEX nrk_nynorsk_article_ts_vector_idx;",
        )
    ]
