# Generated by Django 3.1rc1 on 2020-08-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrk_nynorsk", "0002_auto_20200720_1929"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSFeed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
                ("last_checked", models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
