# Generated by Django 3.1rc1 on 2020-08-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrk_nynorsk", "0003_rssfeed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rssfeed", name="url", field=models.TextField(unique=True),
        ),
    ]
