# Generated by Django 3.1rc1 on 2020-08-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nrk_nynorsk", "0004_auto_20200801_1349"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="publication_date", field=models.DateTimeField(),
        ),
    ]
