# Generated by Django 3.1.2 on 2020-12-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nrk_nynorsk", "0005_auto_20200802_0629"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rssfeed", options={"verbose_name": "RSS feed"},
        ),
    ]
